
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("b8024401-1d8b-4f7e-a8d2-df7396778fd8")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("LibDataModel", "LIB_PRICE_LISTLIB_TRANSACTION", "LIB_PRICE_LIST", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(LIB_PRICE_LIST), "LIB_TRANSACTION", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(LIB_TRANSACTION), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class LibDataEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new LibDataEntities object using the connection string found in the 'LibDataEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=LibDataEntities", "LibDataEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new LibDataEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "LibDataEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new LibDataEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "LibDataEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property LIB_PRICE_LIST() As ObjectSet(Of LIB_PRICE_LIST)
        Get
            If (_LIB_PRICE_LIST Is Nothing) Then
                _LIB_PRICE_LIST = MyBase.CreateObjectSet(Of LIB_PRICE_LIST)("LIB_PRICE_LIST")
            End If
            Return _LIB_PRICE_LIST
        End Get
    End Property

    Private _LIB_PRICE_LIST As ObjectSet(Of LIB_PRICE_LIST)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property LIB_TRANSACTION() As ObjectSet(Of LIB_TRANSACTION)
        Get
            If (_LIB_TRANSACTION Is Nothing) Then
                _LIB_TRANSACTION = MyBase.CreateObjectSet(Of LIB_TRANSACTION)("LIB_TRANSACTION")
            End If
            Return _LIB_TRANSACTION
        End Get
    End Property

    Private _LIB_TRANSACTION As ObjectSet(Of LIB_TRANSACTION)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the LIB_PRICE_LIST EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToLIB_PRICE_LIST(ByVal lIB_PRICE_LIST As LIB_PRICE_LIST)
        MyBase.AddObject("LIB_PRICE_LIST", lIB_PRICE_LIST)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the LIB_TRANSACTION EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToLIB_TRANSACTION(ByVal lIB_TRANSACTION As LIB_TRANSACTION)
        MyBase.AddObject("LIB_TRANSACTION", lIB_TRANSACTION)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="LibDataModel", Name:="LIB_PRICE_LIST")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class LIB_PRICE_LIST
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new LIB_PRICE_LIST object.
    ''' </summary>
    ''' <param name="lIBPLID">Initial value of the LIBPLID property.</param>
    Public Shared Function CreateLIB_PRICE_LIST(lIBPLID As Global.System.String) As LIB_PRICE_LIST
        Dim lIB_PRICE_LIST as LIB_PRICE_LIST = New LIB_PRICE_LIST
        lIB_PRICE_LIST.LIBPLID = lIBPLID
        Return lIB_PRICE_LIST
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LIBPLID() As Global.System.String
        Get
            Return _LIBPLID
        End Get
        Set
            If (_LIBPLID <> Value) Then
                OnLIBPLIDChanging(value)
                ReportPropertyChanging("LIBPLID")
                _LIBPLID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("LIBPLID")
                OnLIBPLIDChanged()
            End If
        End Set
    End Property

    Private _LIBPLID As Global.System.String
    Private Partial Sub OnLIBPLIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLIBPLIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PLITEMNAME() As Global.System.String
        Get
            Return _PLITEMNAME
        End Get
        Set
            OnPLITEMNAMEChanging(value)
            ReportPropertyChanging("PLITEMNAME")
            _PLITEMNAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("PLITEMNAME")
            OnPLITEMNAMEChanged()
        End Set
    End Property

    Private _PLITEMNAME As Global.System.String
    Private Partial Sub OnPLITEMNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPLITEMNAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PLPRICE() As Nullable(Of Global.System.Decimal)
        Get
            Return _PLPRICE
        End Get
        Set
            OnPLPRICEChanging(value)
            ReportPropertyChanging("PLPRICE")
            _PLPRICE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PLPRICE")
            OnPLPRICEChanged()
        End Set
    End Property

    Private _PLPRICE As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnPLPRICEChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnPLPRICEChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("LibDataModel", "LIB_PRICE_LISTLIB_TRANSACTION", "LIB_TRANSACTION")>
     Public Property LIB_TRANSACTION() As EntityCollection(Of LIB_TRANSACTION)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of LIB_TRANSACTION)("LibDataModel.LIB_PRICE_LISTLIB_TRANSACTION", "LIB_TRANSACTION")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of LIB_TRANSACTION)("LibDataModel.LIB_PRICE_LISTLIB_TRANSACTION", "LIB_TRANSACTION", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="LibDataModel", Name:="LIB_TRANSACTION")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class LIB_TRANSACTION
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new LIB_TRANSACTION object.
    ''' </summary>
    ''' <param name="lIBSALEID">Initial value of the LIBSALEID property.</param>
    ''' <param name="lIB_PRICE_LISTLIBPLID">Initial value of the LIB_PRICE_LISTLIBPLID property.</param>
    Public Shared Function CreateLIB_TRANSACTION(lIBSALEID As Global.System.String, lIB_PRICE_LISTLIBPLID As Global.System.String) As LIB_TRANSACTION
        Dim lIB_TRANSACTION as LIB_TRANSACTION = New LIB_TRANSACTION
        lIB_TRANSACTION.LIBSALEID = lIBSALEID
        lIB_TRANSACTION.LIB_PRICE_LISTLIBPLID = lIB_PRICE_LISTLIBPLID
        Return lIB_TRANSACTION
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LIBSALEID() As Global.System.String
        Get
            Return _LIBSALEID
        End Get
        Set
            If (_LIBSALEID <> Value) Then
                OnLIBSALEIDChanging(value)
                ReportPropertyChanging("LIBSALEID")
                _LIBSALEID = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("LIBSALEID")
                OnLIBSALEIDChanged()
            End If
        End Set
    End Property

    Private _LIBSALEID As Global.System.String
    Private Partial Sub OnLIBSALEIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLIBSALEIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LIBLINE() As Nullable(Of Global.System.Decimal)
        Get
            Return _LIBLINE
        End Get
        Set
            OnLIBLINEChanging(value)
            ReportPropertyChanging("LIBLINE")
            _LIBLINE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LIBLINE")
            OnLIBLINEChanged()
        End Set
    End Property

    Private _LIBLINE As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnLIBLINEChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnLIBLINEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LIBPCODE() As Global.System.String
        Get
            Return _LIBPCODE
        End Get
        Set
            OnLIBPCODEChanging(value)
            ReportPropertyChanging("LIBPCODE")
            _LIBPCODE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("LIBPCODE")
            OnLIBPCODEChanged()
        End Set
    End Property

    Private _LIBPCODE As Global.System.String
    Private Partial Sub OnLIBPCODEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLIBPCODEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LIBITEMS() As Nullable(Of Global.System.Decimal)
        Get
            Return _LIBITEMS
        End Get
        Set
            OnLIBITEMSChanging(value)
            ReportPropertyChanging("LIBITEMS")
            _LIBITEMS = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LIBITEMS")
            OnLIBITEMSChanged()
        End Set
    End Property

    Private _LIBITEMS As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnLIBITEMSChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnLIBITEMSChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LIBCASH() As Nullable(Of Global.System.Decimal)
        Get
            Return _LIBCASH
        End Get
        Set
            OnLIBCASHChanging(value)
            ReportPropertyChanging("LIBCASH")
            _LIBCASH = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LIBCASH")
            OnLIBCASHChanged()
        End Set
    End Property

    Private _LIBCASH As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnLIBCASHChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnLIBCASHChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CHK() As Nullable(Of Global.System.Decimal)
        Get
            Return _CHK
        End Get
        Set
            OnCHKChanging(value)
            ReportPropertyChanging("CHK")
            _CHK = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CHK")
            OnCHKChanged()
        End Set
    End Property

    Private _CHK As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnCHKChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnCHKChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LIBPDATE() As Nullable(Of Global.System.DateTime)
        Get
            Return _LIBPDATE
        End Get
        Set
            OnLIBPDATEChanging(value)
            ReportPropertyChanging("LIBPDATE")
            _LIBPDATE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LIBPDATE")
            OnLIBPDATEChanged()
        End Set
    End Property

    Private _LIBPDATE As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnLIBPDATEChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnLIBPDATEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LIBPTIME() As Nullable(Of Global.System.DateTime)
        Get
            Return _LIBPTIME
        End Get
        Set
            OnLIBPTIMEChanging(value)
            ReportPropertyChanging("LIBPTIME")
            _LIBPTIME = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LIBPTIME")
            OnLIBPTIMEChanged()
        End Set
    End Property

    Private _LIBPTIME As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnLIBPTIMEChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnLIBPTIMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ORAUPDATE() As Global.System.String
        Get
            Return _ORAUPDATE
        End Get
        Set
            OnORAUPDATEChanging(value)
            ReportPropertyChanging("ORAUPDATE")
            _ORAUPDATE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ORAUPDATE")
            OnORAUPDATEChanged()
        End Set
    End Property

    Private _ORAUPDATE As Global.System.String
    Private Partial Sub OnORAUPDATEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnORAUPDATEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PTYPE() As Global.System.String
        Get
            Return _PTYPE
        End Get
        Set
            OnPTYPEChanging(value)
            ReportPropertyChanging("PTYPE")
            _PTYPE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("PTYPE")
            OnPTYPEChanged()
        End Set
    End Property

    Private _PTYPE As Global.System.String
    Private Partial Sub OnPTYPEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPTYPEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LIBLPID() As Global.System.String
        Get
            Return _LIBLPID
        End Get
        Set
            OnLIBLPIDChanging(value)
            ReportPropertyChanging("LIBLPID")
            _LIBLPID = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("LIBLPID")
            OnLIBLPIDChanged()
        End Set
    End Property

    Private _LIBLPID As Global.System.String
    Private Partial Sub OnLIBLPIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLIBLPIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LIB_PRICE_LISTLIBPLID() As Global.System.String
        Get
            Return _LIB_PRICE_LISTLIBPLID
        End Get
        Set
            OnLIB_PRICE_LISTLIBPLIDChanging(value)
            ReportPropertyChanging("LIB_PRICE_LISTLIBPLID")
            _LIB_PRICE_LISTLIBPLID = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("LIB_PRICE_LISTLIBPLID")
            OnLIB_PRICE_LISTLIBPLIDChanged()
        End Set
    End Property

    Private _LIB_PRICE_LISTLIBPLID As Global.System.String
    Private Partial Sub OnLIB_PRICE_LISTLIBPLIDChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLIB_PRICE_LISTLIBPLIDChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("LibDataModel", "LIB_PRICE_LISTLIB_TRANSACTION", "LIB_PRICE_LIST")>
    Public Property LIB_PRICE_LIST() As LIB_PRICE_LIST
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of LIB_PRICE_LIST)("LibDataModel.LIB_PRICE_LISTLIB_TRANSACTION", "LIB_PRICE_LIST").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of LIB_PRICE_LIST)("LibDataModel.LIB_PRICE_LISTLIB_TRANSACTION", "LIB_PRICE_LIST").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property LIB_PRICE_LISTReference() As EntityReference(Of LIB_PRICE_LIST)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of LIB_PRICE_LIST)("LibDataModel.LIB_PRICE_LISTLIB_TRANSACTION", "LIB_PRICE_LIST")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of LIB_PRICE_LIST)("LibDataModel.LIB_PRICE_LISTLIB_TRANSACTION", "LIB_PRICE_LIST", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

